// 开发环境服务器地址
var baseURL = 'http://ajax.frontend.itheima.net'
    // // 测试环境服务器地址
    // var baseURL = 'http://ajax.frontend.itheima.net/'
    // // 生产环境服务器地址
    // var baseURL = 'http://ajax.frontend.itheima.net/'



// 拦截所有ajax的请求：grt/post/ajax

// ajaxPrefilter拦截请求然后直行此函数

$.ajaxPrefilter(function(params) {
    // 1.拼接对应环境的服务器地址
    params.url = baseURL + params.url;
    // alert(params.url);


    //2. 对需要权限的接口配置头信息
    // 必须以my开头才行
    if (params.url.indexOf("/my/") !== -1) {
        params.headers = {
                Authorization: localStorage.getItem('token') || ''
            }
            // 3.拦截所有响应，判断身份认证信息
        params.complete = function(res) {
            // console.log(res.responseJSON);
            var obj = res.responseJSON;
            if (obj.status == 1 && obj.message == '身份认证失败！') {
                // 1.情况本地token
                localStorage.removeItem('token');
                // 2.页面跳转
                location.href = '/login.html'
            }
        }
    }

})